server:
  port: 8080

spring:
  jpa:
    show-sql: true
  datasources:
    tenant1:
      url: jdbc:mysql://localhost:3306/tenant1?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    tenant2:
      url: jdbc:mysql://localhost:3306/tenant2?createDatabaseIfNotExist=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver